export const cardImages: Map<string, string> = new Map(Object.entries({
    // Special Cards
    mahjong: './res/mahjong.png',
    phoenix: './res/phoenix.png',
    dogs: './res/dogs.png',
    dragon: './res/dragon.png',
    // Red cards
    red_2: './res/red_2.png',
    red_3: './res/red_3.png',
    red_4: './res/red_4.png',
    red_5: './res/red_5.png',
    red_6: './res/red_6.png',
    red_7: './res/red_7.png',
    red_8: './res/red_8.png',
    red_9: './res/red_9.png',
    red_10: './res/red_10.png',
    red_J: './res/red_J.png',
    red_Q: './res/red_Q.png',
    red_K: './res/red_K.png',
    red_A: './res/red_A.png',
    // Blue cards
    blue_2: './res/blue_2.png',
    blue_3: './res/blue_3.png',
    blue_4: './res/blue_4.png',
    blue_5: './res/blue_5.png',
    blue_6: './res/blue_6.png',
    blue_7: './res/blue_7.png',
    blue_8: './res/blue_8.png',
    blue_9: './res/blue_9.png',
    blue_10: './res/blue_10.png',
    blue_J: './res/blue_J.png',
    blue_Q: './res/blue_Q.png',
    blue_K: './res/blue_K.png',
    blue_A: './res/blue_A.png',
    // Green cards
    green_2: './res/green_2.png',
    green_3: './res/green_3.png',
    green_4: './res/green_4.png',
    green_5: './res/green_5.png',
    green_6: './res/green_6.png',
    green_7: './res/green_7.png',
    green_8: './res/green_8.png',
    green_9: './res/green_9.png',
    green_10: './res/green_10.png',
    green_J: './res/green_J.png',
    green_Q: './res/green_Q.png',
    green_K: './res/green_K.png',
    green_A: './res/green_A.png',
    // Black cards
    black_2: './res/black_2.png',
    black_3: './res/black_3.png',
    black_4: './res/black_4.png',
    black_5: './res/black_5.png',
    black_6: './res/black_6.png',
    black_7: './res/black_7.png',
    black_8: './res/black_8.png',
    black_9: './res/black_9.png',
    black_10: './res/black_10.png',
    black_J: './res/black_J.png',
    black_Q: './res/black_Q.png',
    black_K: './res/black_K.png',
    black_A: './res/black_A.png',

    cardBackground: './res/background.png',
}));
